version: "3.4"
services:
  device:
    container_name: device
    build:
      dockerfile: Dockerfile
    networks:
      bacnet:
        ipv4_address: 172.24.0.3
    environment:
      - ALFALFA_HOST
      - ALFALFA_SITE_ID
    ports:
      - "47808:47808/udp"
    command: "poetry run python alfalfa_bacnet_bridge/alfalfa_bacnet_bridge.py"
  cli:
    container_name: cli
    build:
      dockerfile: Dockerfile
    networks:
      bacnet:
        ipv4_address: 172.24.0.4
    command: "watch -n 5 poetry run python alfalfa_bacnet_bridge/discover_points.py"
networks:
  bacnet:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"